language: node_js
node_js:
  - 0.10

notifications:
  email: false

branches:
  only:
    - development

cache:
  directories:
    - node_modules

before_install:
  - npm install -g codeclimate-test-reporter

after_script:
  - node Build/PublishCodeCoverage.js